apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mall-basic
  labels:
    mall-basic: mysql
spec:
  containers:
    - name: mysql1
      image: "mall-mysql:5.7"
      imagePullPolicy: Never
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
      ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP

