apiVersion: v1
kind: Pod
metadata:
  name: zipkin
  namespace: mall-basic
  labels:
    mall-basic: zipkin
spec:
  containers:
    - name: zipkin
      image: "openzipkin/zipkin"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9411
          name: zipkin
          protocol: TCP
