apiVersion: v1
kind: Pod
metadata:
  name: mall-application
  namespace: mall-basic
  labels:
    mall: application
spec:
  containers:
    - name: zuul
      image: "mall-zuul:0.1"
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
          name: zuul
          protocol: TCP
    - name: member
      image: "mall-member:0.1"
      imagePullPolicy: Never
      ports:
        - containerPort: 8001
          name: member
          protocol: TCP
    - name: seckill
      image: "mall-seckill:0.1"
      imagePullPolicy: Never
      ports:
        - containerPort: 8002
          name: seckill
          protocol: TCP
    - name: goods
      image: "mall-goods:0.1"
      imagePullPolicy: Never
      ports:
        - containerPort: 8003
          name: goods
          protocol: TCP
    - name: remarks
      image: "mall-remarks:0.1"
      imagePullPolicy: Never
      ports:
        - containerPort: 8004
          name: remarks
          protocol: TCP
    - name: order
      image: "mall-order:0.1"
      imagePullPolicy: Never
      ports:
        - containerPort: 8005
          name: order
          protocol: TCP
  initContainers:
    - name: init-eureka
      image: "yauritux/busybox-curl"
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'var1="000";
                                       until [ "$var1" == "200" ];
                                       do echo waiting for mall-eureka;
                                       var1=`curl -I -m 10 -o /dev/null -s -w %{http_code}  eureka-port.mall-basic:8080`;
                                       sleep 2;
                                       done;
                                       echo mall-eureka started!']
    - name: init-rabbitmq
      image: "yauritux/busybox-curl"
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'var1="000";
                                      until [ "$var1" == "200" ];
                                      do echo waiting for mall-rabbitmq;
                                      var1=`curl -I -m 10 -o /dev/null -s -w %{http_code}  rabbitmq-port.mall-basic:15672`;
                                      sleep 2;
                                      done;
                                      echo mall-rabbitmq started!']
    - name: init-zipkin
      image: "yauritux/busybox-curl"
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'var1="000";
                                      until [ "$var1" == "302" ];
                                      do echo waiting for mall-zipkin;
                                      var1=`curl -I -m 10 -o /dev/null -s -w %{http_code}  zipkin-port.mall-basic:9411`;
                                      sleep 2;
                                      done;
                                      echo mall-zipkin started!']
    - name: init-es
      image: "yauritux/busybox-curl"
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'var1="000";
                               until [ "$var1" == "200" ];
                               do echo waiting for elasticsearch;
                               var1=`curl -I -m 10 -o /dev/null -s -w %{http_code}  es-port.mall-basic:9200`;
                               sleep 2;
                               done;
                               echo elasticsearch started!']
