apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  namespace: mall-basic
  labels:
    mall-basic: rabbitmq
spec:
  containers:
    - name: rabbitmq
      image: "rabbitmq:3.8.2-management"
      imagePullPolicy: IfNotPresent
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: root
        - name: RABBITMQ_DEFAULT_PASS
          value: root
      ports:
        - containerPort: 5672
          name: rabbit
          protocol: TCP
        - containerPort: 15672
          name: manager
          protocol: TCP
