apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: mall-basic
  labels:
    mall-basic: redis
spec:
  containers:
    - name: redis
      image: "redis"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
