apiVersion: v1
kind: Pod
metadata:
  name: apollo-portal
  namespace: mall-basic
  labels:
    mall-basic: apollo-portal
spec:
  containers:
    - name: apollo-portal
      image: "mall-apollo-portal:0.1"
      imagePullPolicy: Never
      ports:
        - containerPort: 8070
          name: portal
          protocol: TCP
      volumeMounts:
        - mountPath: /opt
          name: portallogs
  volumes:
    - name: portallogs
      hostPath:
        path:  /c/Users/Administrator/opt/portal
        type: Directory
  initContainers:
    - name: init-admin
      image: "yauritux/busybox-curl"
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'var1="000";
                          until [ "$var1" == "200" ];
                          do echo waiting for admin;
                          var1=`curl -I -m 10 -o /dev/null -s -w %{http_code}  admin-port.mall-basic:8090`;
                          sleep 2;
                          done;
                          echo admin admin!']
#  restartPolicy: Never
